import os
import re
import tempfile

import requests
import streamlit as st
from fpdf import FPDF

from resume_analyzer import analyze_resume


# ============================================================
# MODERN PDF ENGINE & CLASS DEFINITION
# ============================================================

class ModernReportPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_margins(15, 15, 15)
        self.set_auto_page_break(auto=True, margin=18)

    def header(self):
        # Top Accent Banner
        self.set_fill_color(30, 27, 75)  # Deep Indigo (#1E1B4B)
        self.rect(0, 0, 210, 12, style="F")
        self.set_fill_color(79, 70, 229)  # Accent Indigo (#4F46E5)
        self.rect(0, 12, 210, 2, style="F")

        # Running Header Text
        self.set_y(15)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(148, 163, 184)  # Slate Muted
        self.cell(0, 5, "ENTERPRISE AI RESUME ANALYTICS REPORT", new_x="LMARGIN", new_y="NEXT", align="R")
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(148, 163, 184)
        
        # Divider Line
        self.set_draw_color(226, 232, 240)
        self.line(15, 282, 195, 282)

        # Left side: Confidentiality note; Right side: Page Numbering
        self.cell(100, 10, "Confidential - Generated by AI Career Assistant", align="L")
        self.cell(80, 10, f"Page {self.page_no()}", align="R")


def sanitize_pdf_text(text: str, max_word_len: int = 20) -> str:
    """Prepare text for safe rendering in FPDF's cell/multi_cell.
    Guards against FPDF's 'Not enough horizontal space' error by:
      1. Forcing a space after common punctuation.
      2. Breaking individual long tokens into space-joined chunks.
    """
    if not text:
        return ""

    text = str(text)
    text = re.sub(r'([,;:!?/])([^\s])', r'\1 \2', text)
    text = re.sub(r'\s+', ' ', text).strip()

    safe_tokens = []
    for word in text.split(' '):
        if len(word) <= max_word_len:
            safe_tokens.append(word)
            continue
        chunks = [word[i:i + max_word_len] for i in range(0, len(word), max_word_len)]
        safe_tokens.append(' '.join(chunks))

    return ' '.join(safe_tokens)


def safe_multi_cell(
    pdf,
    w: float,
    h: float,
    text: str,
    max_word_len: int = 20,
    min_effective_width_mm: float = 15.0,
    **kwargs,
) -> None:
    """Defensive wrapper around FPDF.multi_cell that prevents line-overflow crashes."""
    safe_text = sanitize_pdf_text(text, max_word_len=max_word_len)
    safe_text = safe_text.encode('latin-1', 'replace').decode('latin-1')

    if not safe_text:
        return

    effective_width = w if w > 0 else (pdf.w - pdf.r_margin - pdf.x)
    if effective_width < min_effective_width_mm:
        pdf.ln(h)
        pdf.set_x(pdf.l_margin)
        w = 0

    try:
        pdf.multi_cell(w, h, safe_text, **kwargs)
    except Exception:
        current_size = pdf.font_size_pt
        pdf.set_font_size(max(current_size - 2, 6))
        forced_break = ' '.join(safe_text[i:i + 8] for i in range(0, len(safe_text), 8))
        pdf.multi_cell(w, h, forced_break, **kwargs)
        pdf.set_font_size(current_size)


def draw_section_heading(pdf, title: str):
    """Draws a stylish modern section header with background pill."""
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(241, 245, 249)  # Light Slate Tint
    pdf.set_text_color(30, 41, 59)     # Slate Dark Text
    pdf.cell(180, 8, f"  {title}", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(3)


def generate_pdf_report(predicted_category, confidence, ats_res, feature_dict, logo_path=None):
    """Generate a downloadable, high-aesthetic PDF report for a single resume analysis."""
    pdf = ModernReportPDF()
    pdf.add_page()

    # ----------------------------------------------------
    # BRAND HEADER & LOGO INTEGRATION
    # ----------------------------------------------------
    start_y = pdf.get_y()
    
    # Render Logo if provided and valid
    if logo_path and os.path.exists(logo_path):
        try:
            pdf.image(logo_path, x=15, y=start_y, w=20)
            text_x = 38
        except Exception:
            text_x = 15
    else:
        text_x = 15

    pdf.set_xy(text_x, start_y)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(15, 23, 42)  # Charcoal
    pdf.cell(0, 8, "Resume Analysis & ATS Audit", new_x="LMARGIN", new_y="NEXT")

    pdf.set_x(text_x)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 116, 139)  # Slate Muted
    pdf.cell(0, 5, "Automated Diagnostic Profile & Candidate Metrics", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_y(max(pdf.get_y() + 4, start_y + 22))
    pdf.set_draw_color(226, 232, 240)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(5)

    # ----------------------------------------------------
    # SECTION 1: CATEGORIZATION SUMMARY
    # ----------------------------------------------------
    draw_section_heading(pdf, "1. CAREER PREDICTION & CONFIDENCE")

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(71, 85, 105)
    
    # Key-Value Info Cards
    pdf.cell(90, 6, "Predicted Job Category:", new_x="RIGHT", new_y="TOP")
    pdf.cell(90, 6, "Model Match Confidence:", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(79, 70, 229)  # Primary Indigo Color
    safe_multi_cell(pdf, 90, 7, str(predicted_category))
    
    pdf.set_xy(105, pdf.get_y() - 7)
    pdf.set_text_color(16, 185, 129)  # Success Emerald Color
    safe_multi_cell(pdf, 90, 7, str(confidence))
    pdf.ln(4)

    # ----------------------------------------------------
    # SECTION 2: ATS MATCH & SKILL GAP ANALYSIS
    # ----------------------------------------------------
    draw_section_heading(pdf, "2. ATS MATCH & SKILL GAP ANALYSIS")

    ats_score = ats_res.get("ats_score", 0)
    
    # Score Summary Banner Card
    pdf.set_fill_color(248, 250, 252)
    pdf.rect(15, pdf.get_y(), 180, 16, style="F")
    
    pdf.set_xy(20, pdf.get_y() + 3)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(51, 65, 85)
    pdf.cell(50, 10, "Overall ATS Score:")

    pdf.set_font("Helvetica", "B", 16)
    if ats_score >= 75:
        pdf.set_text_color(16, 185, 129)  # Green
    elif ats_score >= 50:
        pdf.set_text_color(245, 158, 11)  # Amber
    else:
        pdf.set_text_color(244, 63, 94)   # Red
    
    pdf.cell(30, 10, f"{ats_score:.1f}%")

    matched_skills = ats_res.get('matched_skills', [])
    missing_skills = ats_res.get('missing_skills', [])
    jd_count = ats_res.get('jd_skill_count', len(matched_skills) + len(missing_skills))

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 10, f"Skill Match Coverage: {len(matched_skills)} / {jd_count} required skills", new_x="LMARGIN", new_y="NEXT", align="R")
    pdf.ln(6)

    # Matched Skills Box
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(16, 185, 129)
    pdf.cell(0, 6, "Matched Skills", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(51, 65, 85)
    matched_str = ", ".join(matched_skills) if matched_skills else "None Identified"
    safe_multi_cell(pdf, 180, 5, matched_str)
    pdf.ln(3)

    # Missing Skills Box (Gap Analysis)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(244, 63, 94)
    pdf.cell(0, 6, "Missing Skills (Gap Analysis)", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(51, 65, 85)
    missing_str = ", ".join(missing_skills) if missing_skills else "No Critical Skill Gaps Found"
    safe_multi_cell(pdf, 180, 5, missing_str)
    pdf.ln(4)

    # ----------------------------------------------------
    # SECTION 3: RESUME METRICS GRID
    # ----------------------------------------------------
    draw_section_heading(pdf, "3. STRUCTURAL & TEXT METRICS")

    # Clean Styled Metrics Table
    metrics_data = [
        ("Total Word Count", str(feature_dict.get('word_count', 0))),
        ("Unique Words Detected", str(feature_dict.get('unique_word_count', 0))),
        ("Total Technical Skills Detected", str(feature_dict.get('skill_count', 0))),
        ("Email Contact Present", "Yes" if feature_dict.get('email_present') in [1, True] else "No"),
        ("Phone Contact Present", "Yes" if feature_dict.get('phone_present') in [1, True] else "No"),
    ]

    pdf.set_font("Helvetica", "", 9)
    fill = False
    for label, val in metrics_data:
        pdf.set_fill_color(248, 250, 252) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(120, 7, f"  {label}", border="B", fill=fill)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(60, 7, val, border="B", new_x="LMARGIN", new_y="NEXT", align="C", fill=fill)
        pdf.set_font("Helvetica", "", 9)
        fill = not fill

    return bytes(pdf.output())


# ============================================================
# CONFIGURATION
# ============================================================

API_URL = "http://127.0.0.1:8080/v1/chat/completions"

SYSTEM_PROMPT = """You are an AI Career Assistant.

Give practical, specific and structured career advice.

Help with:
- career planning
- skill gaps
- resumes
- projects
- job preparation
- interviews
- AI/ML careers
- learning roadmaps

Always answer the complete question.

Use headings, bullet points, and actionable steps."""

st.set_page_config(
    page_title="AI Career Assistant",
    page_icon="🧭",
    layout="wide",
)


# ============================================================
# OBSIDIAN GLASS DESIGN SYSTEM
# ============================================================

CUSTOM_CSS = """<style>
@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@500;600&display=swap');

:root {
    --bg-dark: #0B0F17;
    --bg-surface: rgba(18, 24, 38, 0.7);
    --bg-card: rgba(26, 34, 52, 0.65);
    --border: rgba(255, 255, 255, 0.08);
    --border-glow: rgba(99, 102, 241, 0.3);
    --primary: #6366F1;
    --cyan: #06B6D4;
    --teal: #10B981;
    --amber: #F59E0B;
    --rust: #F43F5E;
    --text-main: #F8FAFC;
    --text-muted: #94A3B8;
}

html, body, [class*="css"] {
    font-family: 'Plus Jakarta Sans', sans-serif !important;
}

.stApp,
[data-testid="stAppViewContainer"],
[data-testid="stMain"],
[data-testid="stHeader"] {
    background: radial-gradient(circle at 50% -20%, #1E1B4B 0%, #0B0F17 80%) !important;
    color: var(--text-main) !important;
}

[data-testid="stSidebar"] {
    background: rgba(11, 15, 23, 0.9) !important;
    border-right: 1px solid var(--border) !important;
}

h1, h2, h3, h4 {
    color: var(--text-main) !important;
    font-weight: 700 !important;
    letter-spacing: -0.02em !important;
}

[data-testid="stMarkdownContainer"] p,
[data-testid="stMarkdownContainer"] li,
[data-testid="stMarkdownContainer"] span,
[data-testid="stWidgetLabel"] p,
[data-testid="stWidgetLabel"] label,
[data-testid="stCaptionContainer"] {
    color: var(--text-muted) !important;
}

hr { border-color: var(--border) !important; }

.hero {
    position: relative;
    overflow: hidden;
    background: linear-gradient(135deg, rgba(99, 102, 241, 0.15) 0%, rgba(6, 182, 212, 0.08) 100%);
    border: 1px solid var(--border-glow);
    backdrop-filter: blur(16px);
    border-radius: 20px;
    padding: 32px 40px;
    margin-bottom: 24px;
    box-shadow: 0 20px 40px rgba(0, 0, 0, 0.4);
}
.hero-compass {
    position: absolute;
    top: -20px;
    right: -20px;
    width: 240px;
    height: 240px;
    opacity: 0.8;
    pointer-events: none;
}
.compass-needle {
    transform-origin: 100px 100px;
    animation: spin 24s linear infinite;
}
@keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
}
.hero-eyebrow {
    font-family: 'JetBrains Mono', monospace;
    font-size: 11px;
    letter-spacing: 0.18em;
    text-transform: uppercase;
    color: var(--cyan);
    margin-bottom: 12px;
}
.hero-title {
    font-size: 32px;
    font-weight: 800;
    color: #FFFFFF !important;
    margin: 0 0 10px 0;
    max-width: 650px;
    line-height: 1.2;
}
.hero-subtitle {
    font-size: 15px;
    color: var(--text-muted) !important;
    margin: 0;
    max-width: 620px;
    line-height: 1.6;
}
.hero-stats {
    display: flex;
    gap: 32px;
    margin-top: 20px;
    flex-wrap: wrap;
}
.hero-stat-label {
    font-family: 'JetBrains Mono', monospace;
    font-size: 10px;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--text-muted);
}
.hero-stat-value {
    font-size: 15px;
    font-weight: 700;
    color: var(--cyan);
}

.section-tag {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-family: 'JetBrains Mono', monospace;
    font-size: 11px;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--cyan);
    background: rgba(6, 182, 212, 0.12);
    border: 1px solid rgba(6, 182, 212, 0.25);
    border-radius: 999px;
    padding: 4px 12px;
    margin-bottom: 8px;
}

.stButton > button, div[data-testid="stDownloadButton"] > button {
    font-weight: 600;
    border-radius: 12px;
    border: 1px solid var(--primary);
    background: linear-gradient(135deg, var(--primary) 0%, #4F46E5 100%);
    color: #FFFFFF !important;
    padding: 0.6em 1.2em;
    transition: all 0.2s ease;
    box-shadow: 0 4px 12px rgba(99, 102, 241, 0.25);
}
.stButton > button p, div[data-testid="stDownloadButton"] > button p { color: #FFFFFF !important; }
.stButton > button:hover, div[data-testid="stDownloadButton"] > button:hover {
    transform: translateY(-1px);
    box-shadow: 0 6px 18px rgba(99, 102, 241, 0.4);
    border-color: var(--cyan);
}

div[data-testid="stVerticalBlockBorderWrapper"] > div {
    background: var(--bg-card);
    backdrop-filter: blur(12px);
    border-radius: 16px;
    border: 1px solid var(--border);
}
div[data-testid="stVerticalBlockBorderWrapper"] {
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.25);
    border-radius: 16px;
    margin-bottom: 8px;
}

div[data-testid="stExpander"] {
    border: 1px solid var(--border) !important;
    border-radius: 14px !important;
    background: var(--bg-card);
}
div[data-testid="stExpander"] summary span { color: var(--text-main) !important; }

div[data-testid="stFileUploaderDropzone"] {
    background: rgba(18, 24, 38, 0.5) !important;
    border: 1.5px dashed var(--border-glow);
    border-radius: 14px;
}
div[data-testid="stFileUploaderDropzone"] p,
div[data-testid="stFileUploaderDropzone"] span,
div[data-testid="stFileUploaderDropzone"] small {
    color: var(--text-muted) !important;
}

.pill {
    display: inline-block;
    font-family: 'JetBrains Mono', monospace;
    font-size: 12px;
    font-weight: 500;
    padding: 5px 12px;
    margin: 4px 6px 4px 0;
    border-radius: 999px;
    border: 1px solid var(--border);
    background: rgba(255, 255, 255, 0.05);
    color: var(--text-main);
}
.pill-teal { background: rgba(16, 185, 129, 0.15); border-color: rgba(16, 185, 129, 0.3); color: var(--teal); }
.pill-amber { background: rgba(245, 158, 11, 0.15); border-color: rgba(245, 158, 11, 0.3); color: var(--amber); }
.pill-rust { background: rgba(244, 63, 94, 0.15); border-color: rgba(244, 63, 94, 0.3); color: var(--rust); }

.gauge-wrap {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 12px;
}
.gauge {
    width: 140px;
    height: 140px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    position: relative;
}
.gauge::before {
    content: "";
    position: absolute;
    inset: 12px;
    background: #0D131F;
    border-radius: 50%;
    box-shadow: inset 0 0 10px rgba(0, 0, 0, 0.8);
}
.gauge-inner {
    position: relative;
    z-index: 1;
    display: flex;
    align-items: baseline;
    gap: 2px;
}
.gauge-value {
    font-size: 32px;
    font-weight: 800;
    color: var(--text-main);
}
.gauge-suffix {
    font-family: 'JetBrains Mono', monospace;
    font-size: 14px;
    color: var(--text-muted);
}
.gauge-label {
    font-family: 'JetBrains Mono', monospace;
    font-size: 11px;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: var(--text-muted);
}

.bar-readout { margin-bottom: 14px; }
.bar-readout-top {
    display: flex;
    justify-content: space-between;
    margin-bottom: 4px;
}
.bar-readout-label { font-size: 12px; color: var(--text-muted); }
.bar-readout-value { font-family: 'JetBrains Mono', monospace; font-size: 12px; font-weight: 600; color: var(--cyan); }
.bar-readout-track {
    height: 8px;
    border-radius: 999px;
    background: rgba(255, 255, 255, 0.08);
    overflow: hidden;
}
.bar-readout-fill { height: 100%; border-radius: 999px; }

.subhead {
    font-size: 16px;
    font-weight: 700;
    color: var(--text-main);
    margin-bottom: 4px;
}
</style>"""

try:
    st.html(CUSTOM_CSS)
except AttributeError:
    st.markdown(CUSTOM_CSS, unsafe_allow_html=True)


HERO_COMPASS_SVG = """<svg class="hero-compass" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
  <circle cx="100" cy="100" r="90" stroke="rgba(255,255,255,0.12)" stroke-width="1" fill="none"/>
  <circle cx="100" cy="100" r="65" stroke="rgba(6,182,212,0.2)" stroke-width="1" fill="none"/>
  <circle cx="100" cy="100" r="40" stroke="rgba(99,102,241,0.2)" stroke-width="1" fill="none"/>
  <line x1="100" y1="4" x2="100" y2="20" stroke="rgba(255,255,255,0.3)" stroke-width="1.5"/>
  <line x1="100" y1="180" x2="100" y2="196" stroke="rgba(255,255,255,0.3)" stroke-width="1.5"/>
  <line x1="4" y1="100" x2="20" y2="100" stroke="rgba(255,255,255,0.3)" stroke-width="1.5"/>
  <line x1="180" y1="100" x2="196" y2="100" stroke="rgba(255,255,255,0.3)" stroke-width="1.5"/>
  <line class="compass-needle" x1="100" y1="100" x2="100" y2="32" stroke="#06B6D4" stroke-width="2.5" stroke-linecap="round"/>
  <circle cx="100" cy="100" r="4" fill="#6366F1"/>
</svg>"""


# ============================================================
# DISPLAY HELPERS
# ============================================================

def section_tag(label):
    return f'<div class="section-tag">{label}</div>'


def pills_html(items, variant="slate"):
    if not items:
        return ""
    return "".join(
        f'<span class="pill pill-{variant}">{item}</span>' for item in items
    )


def score_variant(score):
    try:
        score = float(score)
    except (TypeError, ValueError):
        score = 0.0

    if score >= 75:
        return "#10B981", "teal"
    if score >= 50:
        return "#F59E0B", "amber"
    return "#F43F5E", "rust"


def gauge_html(label, score):
    try:
        score = float(score)
    except (TypeError, ValueError):
        score = 0.0

    score = max(0.0, min(100.0, score))
    color, _ = score_variant(score)

    return f"""<div class="gauge-wrap">
        <div class="gauge" style="background: conic-gradient({color} {score}%, rgba(255,255,255,0.08) {score}%);">
            <div class="gauge-inner">
                <span class="gauge-value">{score:.0f}</span>
                <span class="gauge-suffix">%</span>
            </div>
        </div>
        <div class="gauge-label">{label}</div>
    </div>"""


def bar_readout(label, score):
    try:
        score = float(score)
    except (TypeError, ValueError):
        score = 0.0

    score = max(0.0, min(100.0, score))
    color, _ = score_variant(score)

    html_code = f"""<div class="bar-readout">
            <div class="bar-readout-top">
                <span class="bar-readout-label">{label}</span>
                <span class="bar-readout-value">{score:.1f}%</span>
            </div>
            <div class="bar-readout-track">
                <div class="bar-readout-fill" style="width: {score}%; background: {color};"></div>
            </div>
        </div>"""
    try:
        st.html(html_code)
    except AttributeError:
        st.markdown(html_code, unsafe_allow_html=True)


# ============================================================
# SESSION STATE
# ============================================================

if "messages" not in st.session_state:
    st.session_state.messages = []

if "analysis_result" not in st.session_state:
    st.session_state.analysis_result = None

if "analyzed_filename" not in st.session_state:
    st.session_state.analyzed_filename = None


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def save_uploaded_file(uploaded_file):
    suffix = os.path.splitext(uploaded_file.name)[1]
    with tempfile.NamedTemporaryFile(
        delete=False,
        suffix=suffix,
    ) as temp_file:
        temp_file.write(uploaded_file.getbuffer())
        return temp_file.name


def analyze_uploaded_resume(uploaded_file):
    temp_path = None
    try:
        temp_path = save_uploaded_file(uploaded_file)
        result = analyze_resume(temp_path)
        return result, None
    except Exception as e:
        return None, str(e)
    finally:
        if temp_path and os.path.exists(temp_path):
            try:
                os.remove(temp_path)
            except OSError:
                pass


def call_llama_api(messages):
    try:
        response = requests.post(
            API_URL,
            json={
                "messages": messages,
                "temperature": 0.7,
                "max_tokens": 512,
            },
            timeout=120,
        )
        response.raise_for_status()
        data = response.json()
        answer = data["choices"][0]["message"]["content"]
        return answer, None
    except requests.exceptions.ConnectionError:
        return (
            None,
            "Could not connect to the local Llama server. "
            "Make sure llama-server is running on port 8080.",
        )
    except requests.exceptions.Timeout:
        return (
            None,
            "The Llama request timed out. Please try again.",
        )
    except Exception as e:
        return None, f"Llama API error: {e}"


# ============================================================
# HEADER
# ============================================================

hero_html = f"""<div class="hero">
    {HERO_COMPASS_SVG}
    <div class="hero-eyebrow">🧭 CAREER CONTROL ROOM</div>
    <div class="hero-title">Plot your next career move with data, not guesswork.</div>
    <p class="hero-subtitle">
        Upload a resume for an instrument-grade readout — ATS score, skill
        gaps, and job matches — then discuss recommendations side-by-side with your Llama 3.1 career mentor.
    </p>
    <div class="hero-stats">
        <div>
            <div class="hero-stat-label">Intake</div>
            <div class="hero-stat-value">PDF · DOCX</div>
        </div>
        <div>
            <div class="hero-stat-label">Scoring</div>
            <div class="hero-stat-value">ATS + Skill Match</div>
        </div>
        <div>
            <div class="hero-stat-label">Mentor</div>
            <div class="hero-stat-value">Llama 3.1 · Career LoRA</div>
        </div>
    </div>
</div>"""

try:
    st.html(hero_html)
except AttributeError:
    st.markdown(hero_html, unsafe_allow_html=True)


# ============================================================
# SIDE-BY-SIDE TWO-COLUMN LAYOUT
# ============================================================

col_left, col_right = st.columns([1, 1], gap="large")


# ============================================================
# LEFT COLUMN: RESUME ANALYZER
# ============================================================

with col_left:
    st.markdown(section_tag("01 · INTAKE"), unsafe_allow_html=True)
    st.header("AI Resume Analyzer")

    uploaded_file = st.file_uploader(
        "Upload your resume",
        type=["pdf", "docx"],
        help="Upload a PDF or DOCX resume.",
    )

    if uploaded_file is None:
        st.session_state.analysis_result = None
        st.session_state.analyzed_filename = None
    elif st.session_state.analyzed_filename != uploaded_file.name:
        st.session_state.analysis_result = None

    analyze_clicked = st.button(
        "🔍 Analyze Resume",
        type="primary",
        use_container_width=True,
    )

    if uploaded_file is not None and analyze_clicked:
        with st.spinner(
            "Analyzing resume, extracting skills, "
            "matching jobs, and calculating ATS score..."
        ):
            result, error = analyze_uploaded_resume(uploaded_file)

        if error:
            st.error(f"Resume analysis failed: {error}")
            st.session_state.analysis_result = None
            st.session_state.analyzed_filename = None
        else:
            st.session_state.analysis_result = result
            st.session_state.analyzed_filename = uploaded_file.name
            st.success("Resume analyzed successfully.")

    result = st.session_state.analysis_result

    if result is None:
        st.info(
            "Upload a PDF/DOCX resume and click "
            "**Analyze Resume** to begin."
        )
    else:
        st.divider()

        with st.container(border=True):
            st.markdown(section_tag("🎯 PREDICTION"), unsafe_allow_html=True)
            st.header("Career Prediction")

            predicted_career = result.get("predicted_career", "N/A")
            top_careers = result.get("top_careers", [])
            st.success(f"Predicted Career: **{predicted_career}**")

            if top_careers:
                with st.expander("View Top 5 Career Predictions"):
                    for index, career in enumerate(top_careers, start=1):
                        if isinstance(career, tuple) and len(career) >= 2:
                            career_name = career[0]
                            career_score = career[1]
                            st.markdown(
                                f'<div class="subhead">{index}. {career_name}</div>',
                                unsafe_allow_html=True,
                            )
                            st.caption(f"Model score: {career_score:.4f}")
                        else:
                            st.markdown(
                                f'<div class="subhead">{index}. {career}</div>',
                                unsafe_allow_html=True,
                            )

        st.divider()

        with st.container(border=True):
            st.markdown(section_tag("🧠 SKILLS DETECTED"), unsafe_allow_html=True)
            st.header("Extracted Skills")

            skills = result.get("skills", [])
            if skills:
                st.write(f"**Total Skills:** {len(skills)}")
                st.markdown(
                    pills_html(sorted(skills), "slate"),
                    unsafe_allow_html=True,
                )
            else:
                st.info("No skills were detected.")

        st.divider()

        with st.container(border=True):
            st.markdown(section_tag("📊 SCORE PANEL"), unsafe_allow_html=True)
            st.header("ATS Score")

            ats = result.get("ats_score", {})
            overall_ats = ats.get("ats_score", 0)

            gauge_col, breakdown_col = st.columns([1, 2])

            with gauge_col:
                try:
                    st.html(gauge_html("Overall ATS Score", overall_ats))
                except AttributeError:
                    st.markdown(gauge_html("Overall ATS Score", overall_ats), unsafe_allow_html=True)

            with breakdown_col:
                bar_readout("Skill Match (50%)", ats.get("skill_coverage", 0))
                bar_readout("Keyword Quality (15%)", ats.get("uniqueness_score", 0))
                bar_readout("Resume Sections (15%)", ats.get("section_score", 0))

        st.divider()

        # ============================================================
        # RESUME QUALITY / STRUCTURAL METRICS
        # ============================================================
        with st.container(border=True):
            st.markdown(
                section_tag("📋 RESUME QUALITY"),
                unsafe_allow_html=True,
            )
            st.header("Resume Structural & Text Metrics")

            features = result.get("features", {})

            word_count = features.get("word_count", 0)
            unique_word_count = features.get("unique_word_count", 0)
            email_present = bool(features.get("email_present"))
            phone_present = bool(features.get("phone_present"))

            metric_col1, metric_col2, metric_col3 = st.columns(3)

            with metric_col1:
                st.metric("Total Word Count", f"{word_count:,}")

            with metric_col2:
                st.metric("Unique Words Detected", f"{unique_word_count:,}")

            with metric_col3:
                st.metric("Technical Skills Detected", len(skills))

            contact_col1, contact_col2 = st.columns(2)

            with contact_col1:
                st.metric(
                    "Email Contact Present",
                    "Yes" if email_present else "No",
                )

            with contact_col2:
                st.metric(
                    "Phone Contact Present",
                    "Yes" if phone_present else "No",
                )

        st.divider()

        # ============================================================
        # PDF REPORT DOWNLOAD SECTION
        # ============================================================
        with st.container(border=True):
            st.markdown(section_tag("📄 EXPORT REPORT"), unsafe_allow_html=True)
            st.header("Download Analysis PDF")

            cat = result.get("predicted_career", "N/A")

            confidence_val = "High Match"
            if top_careers and isinstance(top_careers[0], tuple) and len(top_careers[0]) >= 2:
                top_score = top_careers[0][1]
                confidence_val = f"{top_score * 100:.1f}% Match" if top_score <= 1.0 else f"{top_score:.2f} Match"

            ats_data = result.get("ats_score", {})
            # Structural/text metrics are returned inside result["features"]
            # by resume_analyzer_intelligent_matching_working.py.
            features = result.get("features", {})

            feat_dict = {
                "word_count": features.get("word_count", 0),
                "unique_word_count": features.get("unique_word_count", 0),
                "skill_count": len(skills),
                "email_present": 1 if features.get("email_present") else 0,
                "phone_present": 1 if features.get("phone_present") else 0,
            }

            # Optional logo path parameter if your app directory contains an app logo PNG/JPG
            logo_file = "logo.png" if os.path.exists("logo.png") else None

            pdf_bytes = generate_pdf_report(
                predicted_category=cat,
                confidence=confidence_val,
                ats_res=ats_data,
                feature_dict=feat_dict,
                logo_path=logo_file,
            )

            st.download_button(
                label="📥 Download Modern PDF Report",
                data=pdf_bytes,
                file_name="Resume_Analysis_Report.pdf",
                mime="application/pdf",
                use_container_width=True,
            )


# ============================================================
# RIGHT COLUMN: AI CAREER MENTOR CHAT
# ============================================================

with col_right:
    st.markdown(section_tag("02 · MENTOR CHAT"), unsafe_allow_html=True)
    st.header("AI Career Mentor")

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.write(message["content"])

    if user_prompt := st.chat_input("Ask your mentor about your resume or career goals..."):
        st.session_state.messages.append({"role": "user", "content": user_prompt})
        with st.chat_message("user"):
            st.write(user_prompt)

        # Build dynamic prompt with resume context
        system_content = SYSTEM_PROMPT
        if st.session_state.get("analysis_result"):
            res = st.session_state.analysis_result
            c_name = res.get("predicted_career", "N/A")
            s_list = ", ".join(res.get("skills", []))
            a_data = res.get("ats_score", {})
            o_ats = a_data.get("ats_score", 0)

            resume_context = f"""

[Analyzed Resume Context]
- Predicted Career Path: {c_name}
- Overall ATS Score: {o_ats:.1f}%
- Skill Coverage Score: {a_data.get('skill_coverage', 0):.1f}%
- Keyword Quality Score: {a_data.get('uniqueness_score', 0):.1f}%
- Detected Skills: {s_list if s_list else 'None'}

Incorporate this candidate context when answering user questions about their resume, skills, gap analysis, or career strategy."""
            system_content += resume_context

        api_messages = [{"role": "system", "content": system_content}]
        api_messages.extend(st.session_state.messages)

        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                answer, error = call_llama_api(api_messages)
                if error:
                    st.error(f"⚠️ {error}")
                    st.session_state.messages.append({"role": "assistant", "content": f"⚠️ {error}"})
                else:
                    st.write(answer)
                    st.session_state.messages.append({"role": "assistant", "content": answer})